const Router = require('express')
const router = new Router()
const animalRouter = require('./animalRouter.js')
const speciesRouter = require('./speciesRouter.js')
const guardianshipRouter = require('./guardianshipRouter.js')
const eventRouter = require('./eventRouter.js')
const newsRouter = require('./newsRouter.js')
const vacancyRouter = require('./vacancyRouter.js')
const serviceRouter = require('./serviceRouter.js')
const ticketRouter = require('./ticketRouter.js')
const newsCategoriesRouter = require('./newsCategoriesRouter.js')
const souvenirRouter = require('./souvenirRouter.js')
const souvenirCategoriesRouter = require('./souvenirCategoriesRouter.js')

router.use('/animal', animalRouter)
router.use('/species', speciesRouter)
router.use('/guardianship', guardianshipRouter)
router.use('/event', eventRouter)
router.use('/news', newsRouter)
router.use('/vacancy', vacancyRouter)
router.use('/service', serviceRouter)
router.use('/ticket', ticketRouter)
router.use('/newsCategories', newsCategoriesRouter)
router.use('/souvenir', souvenirRouter)
router.use('/souvenirCategories', souvenirCategoriesRouter)

module.exports = router